spring.application.name=community-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update

file.post-upload-dir=uploads/posts
file.profile-upload-dir=uploads/profiles

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=55MB

spring.profiles.active=development

jwt.secret=${JWT_SECRET}
jwt.access-token-exp-seconds=300
jwt.refresh-token-exp-seconds=604800
