CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       nickname VARCHAR(30) NOT NULL UNIQUE,
                       profile_stored_filename VARCHAR(500) NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NULL,
                       deleted_at TIMESTAMP NULL,
                       PRIMARY KEY (user_id)
);

CREATE TABLE posts (
                       post_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       writer_id BIGINT NOT NULL,
                       title VARCHAR(26) NOT NULL,
                       content TEXT NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NULL,
                       like_count INT NOT NULL DEFAULT 0 CHECK (like_count >= 0),
                       comment_count INT NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
                       view_count INT NOT NULL DEFAULT 0 CHECK (view_count >= 0),
                       PRIMARY KEY (post_id),
                       FOREIGN KEY (writer_id) REFERENCES users(user_id)
);

CREATE TABLE post_images (
                             post_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             post_id BIGINT NOT NULL,
                             original_filename VARCHAR(500) NOT NULL,
                             stored_filename VARCHAR(100) NOT NULL,
                             image_order INT NOT NULL CHECK (image_order >= 1),
                             UNIQUE (post_id, image_order),
                             UNIQUE (stored_filename),
                             PRIMARY KEY (post_image_id),
                             FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE
);

CREATE TABLE comments (
                          comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          post_id BIGINT NOT NULL,
                          parent_comment_id BIGINT NULL,
                          writer_id BIGINT NOT NULL,
                          content TEXT NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NULL,
                          deleted_at TIMESTAMP NULL,
                          PRIMARY KEY (comment_id),
                          FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
                          FOREIGN KEY (parent_comment_id) REFERENCES comments(comment_id),
                          FOREIGN KEY (writer_id) REFERENCES users(user_id)
);

CREATE TABLE post_likes (
                            post_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            user_id BIGINT NOT NULL,
                            post_id BIGINT NOT NULL,
                            created_at TIMESTAMP NOT NULL,
                            PRIMARY KEY (post_like_id),
                            UNIQUE (user_id, post_id),
                            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                            FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE
);